# Generated by Django 5.2.12 on 2026-03-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='broadcasts/%Y/%m/%d', verbose_name='Картинка')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('ready', 'Готово'), ('sending', 'Отправляется'), ('sent', 'Отправлено')], default='draft', max_length=16, verbose_name='Статус')),
                ('delivered_count', models.PositiveIntegerField(default=0, verbose_name='Доставлено')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='Ошибок')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено в')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярный')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ('sort_order', 'question'),
            },
        ),
    ]
