# Generated by Django 5.2.12 on 2026-03-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='broadcast',
            index=models.Index(fields=['status', '-created_at'], name='broadcast_status_created_idx'),
        ),
    ]
