"""Константы API, сериализаторов и сервисных представлений."""

FAQ_RESULTS_LIMIT = 10
ACTIVE_ORDERS_LIMIT = 20
MAX_CHECKOUT_ADDRESS_LENGTH = 1000
MAX_CART_ITEM_QUANTITY = 1000
MAX_NOTIFICATION_ERROR_LENGTH = 1000
NOTIFICATION_CLAIM_DEFAULT_LIMIT = 10
NOTIFICATION_CLAIM_MIN_LIMIT = 1
NOTIFICATION_CLAIM_MAX_LIMIT = 100
