"""Маршруты backend API."""

from django.urls import path

from apps.api.views import (
    CategoryTreeAPIView,
    FAQInlineAPIView,
    ProductDetailAPIView,
    ProductListAPIView,
    ServiceActiveOrdersAPIView,
    ServiceBroadcastReportAPIView,
    ServiceCartAPIView,
    ServiceCartClearAPIView,
    ServiceCartItemAPIView,
    ServiceCheckoutAPIView,
    ServiceClaimBroadcastAPIView,
    ServiceClaimNotificationsAPIView,
    ServiceCustomerActiveOrdersAPIView,
    ServiceMarkPaidAPIView,
    ServiceNotificationCompleteAPIView,
    ServiceNotificationFailAPIView,
    ServiceOrderStatusAPIView,
    ServiceSettingsAPIView,
    ServiceSmokeCleanupAPIView,
    ServiceSyncCustomerAPIView,
    WebAppCartAPIView,
    WebAppCartClearAPIView,
    WebAppCartItemAPIView,
    WebAppCheckoutAPIView,
    WebAppSessionAPIView,
)

urlpatterns = [
    path(
        'catalog/categories/',
        CategoryTreeAPIView.as_view(),
        name='api-categories',
    ),
    path(
        'catalog/products/', ProductListAPIView.as_view(), name='api-products'
    ),
    path(
        'catalog/products/<int:pk>/',
        ProductDetailAPIView.as_view(),
        name='api-product-detail',
    ),
    path('faq/inline/', FAQInlineAPIView.as_view(), name='api-faq-inline'),
    path(
        'webapp/session/',
        WebAppSessionAPIView.as_view(),
        name='api-webapp-session',
    ),
    path('webapp/cart/', WebAppCartAPIView.as_view(), name='api-webapp-cart'),
    path(
        'webapp/cart/items/',
        WebAppCartItemAPIView.as_view(),
        name='api-webapp-cart-item-create',
    ),
    path(
        'webapp/cart/items/<int:product_id>/',
        WebAppCartItemAPIView.as_view(),
        name='api-webapp-cart-item',
    ),
    path(
        'webapp/cart/clear/',
        WebAppCartClearAPIView.as_view(),
        name='api-webapp-cart-clear',
    ),
    path(
        'webapp/orders/checkout/',
        WebAppCheckoutAPIView.as_view(),
        name='api-webapp-checkout',
    ),
    path(
        'service/customers/sync/',
        ServiceSyncCustomerAPIView.as_view(),
        name='service-sync-customer',
    ),
    path(
        'service/settings/',
        ServiceSettingsAPIView.as_view(),
        name='service-settings',
    ),
    path(
        'service/cart/<int:telegram_id>/',
        ServiceCartAPIView.as_view(),
        name='service-cart',
    ),
    path(
        'service/cart/items/',
        ServiceCartItemAPIView.as_view(),
        name='service-cart-item',
    ),
    path(
        'service/cart/clear/',
        ServiceCartClearAPIView.as_view(),
        name='service-cart-clear',
    ),
    path(
        'service/orders/checkout/',
        ServiceCheckoutAPIView.as_view(),
        name='service-checkout',
    ),
    path(
        'service/orders/<int:order_id>/mark-paid/',
        ServiceMarkPaidAPIView.as_view(),
        name='service-mark-paid',
    ),
    path(
        'service/orders/<int:order_id>/status/',
        ServiceOrderStatusAPIView.as_view(),
        name='service-order-status',
    ),
    path(
        'service/orders/active/',
        ServiceActiveOrdersAPIView.as_view(),
        name='service-active-orders',
    ),
    path(
        'service/orders/customer/<int:telegram_id>/active/',
        ServiceCustomerActiveOrdersAPIView.as_view(),
        name='service-customer-active-orders',
    ),
    path(
        'service/smoke/cleanup/',
        ServiceSmokeCleanupAPIView.as_view(),
        name='service-smoke-cleanup',
    ),
    path(
        'service/notifications/claim/',
        ServiceClaimNotificationsAPIView.as_view(),
        name='service-claim-notifications',
    ),
    path(
        'service/notifications/<int:notification_id>/complete/',
        ServiceNotificationCompleteAPIView.as_view(),
        name='service-notification-complete',
    ),
    path(
        'service/notifications/<int:notification_id>/fail/',
        ServiceNotificationFailAPIView.as_view(),
        name='service-notification-fail',
    ),
    path(
        'service/broadcasts/claim/',
        ServiceClaimBroadcastAPIView.as_view(),
        name='service-broadcast-claim',
    ),
    path(
        'service/broadcasts/<int:broadcast_id>/report/',
        ServiceBroadcastReportAPIView.as_view(),
        name='service-broadcast-report',
    ),
]
