# Generated by Django 5.2.12 on 2026-03-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['status', 'created_at'], name='notif_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['status', 'updated_at'], name='notif_status_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='order_status_created_idx'),
        ),
    ]
