"""Общие константы Django-проекта."""

DEFAULT_WEBAPP_INIT_DATA_MAX_AGE_SECONDS = 86400
DEFAULT_NOTIFICATION_PROCESSING_TIMEOUT_SECONDS = 60
DATABASE_CONN_MAX_AGE_SECONDS = 600
DEFAULT_PAGE_SIZE = 6
LOG_FILE_MAX_BYTES = 5 * 1024 * 1024
LOG_FILE_BACKUP_COUNT = 5
