"""Константы Telegram бота и фоновых задач."""

DEFAULT_HTTP_TIMEOUT_SECONDS = 20
DEFAULT_SETTINGS_CACHE_TTL_SECONDS = 30
DEFAULT_NOTIFICATION_POLL_INTERVAL_SECONDS = 10
DEFAULT_BROADCAST_POLL_INTERVAL_SECONDS = 30
DEFAULT_NOTIFICATION_CLAIM_LIMIT = 10
MAX_NOTIFICATION_ERROR_LENGTH = 1000
MAX_FULL_NAME_LENGTH = 255
MAX_ADDRESS_LENGTH = 1000
TELEGRAM_MEDIA_GROUP_LIMIT = 10
FAQ_INLINE_DESCRIPTION_LIMIT = 70
TEXT_TRUNCATE_LIMIT = 80
BROADCAST_SEND_DELAY_SECONDS = 0.05
BOT_LOG_MAX_BYTES = 5 * 1024 * 1024
BOT_LOG_BACKUP_COUNT = 5
