# Generated by Django 5.2.12 on 2026-03-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID админ-чата')),
                ('catalog_webapp_url', models.URLField(blank=True, verbose_name='URL WebApp')),
                ('help_text', models.TextField(blank=True, default='Используйте /catalog для просмотра каталога и /cart для корзины.', verbose_name='Текст помощи')),
                ('subscription_message', models.TextField(blank=True, default='Для продолжения подпишитесь на обязательные каналы и нажмите кнопку проверки.', verbose_name='Сообщение о подписке')),
            ],
            options={
                'verbose_name': 'Настройки бота',
                'verbose_name_plural': 'Настройки бота',
            },
        ),
        migrations.CreateModel(
            name='RequiredChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='Chat ID')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Username')),
                ('invite_link', models.URLField(blank=True, verbose_name='Ссылка на вступление')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Канал/группа для подписки',
                'verbose_name_plural': 'Каналы/группы для подписки',
                'ordering': ('sort_order', 'title'),
            },
        ),
    ]
